export const initialVisaFormData = {
  visaType: '',
  firstName: '',
  lastName: '',
  gender: '',
  dateOfBirth: '',
  placeOfBirth: '',
  city: '',
  countryOfBirth: '',
  nationalityOrigin: '',
  nationalityCurrent: '',
  address: '',
  cityAddress: '',
  countryAddress: '',
  maritalStatus: '',
  fatherName: '',
  profession: '',
  employer: '',
  employerAddress: '',
};
